"""
This type stub file was generated by pyright.
"""

import ctypes
from .arm_const import *

class ArmOpMem(ctypes.Structure):
    _fields_ = ...


class ArmOpShift(ctypes.Structure):
    _fields_ = ...


class ArmOpValue(ctypes.Union):
    _fields_ = ...


class ArmOp(ctypes.Structure):
    _fields_ = ...
    @property
    def imm(self): # -> Any:
        ...
    
    @property
    def reg(self): # -> Any:
        ...
    
    @property
    def fp(self): # -> Any:
        ...
    
    @property
    def mem(self): # -> Any:
        ...
    
    @property
    def setend(self): # -> Any:
        ...
    


class CsArm(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> tuple[Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, list[Any]]:
    ...

