"""
This type stub file was generated by pyright.
"""

import ctypes
from .arm64_const import *

class Arm64OpMem(ctypes.Structure):
    _fields_ = ...


class Arm64OpShift(ctypes.Structure):
    _fields_ = ...


class Arm64OpValue(ctypes.Union):
    _fields_ = ...


class Arm64Op(ctypes.Structure):
    _fields_ = ...
    @property
    def imm(self): # -> Any:
        ...
    
    @property
    def reg(self): # -> Any:
        ...
    
    @property
    def fp(self): # -> Any:
        ...
    
    @property
    def mem(self): # -> Any:
        ...
    
    @property
    def pstate(self): # -> Any:
        ...
    
    @property
    def sys(self): # -> Any:
        ...
    
    @property
    def prefetch(self): # -> Any:
        ...
    
    @property
    def barrier(self): # -> Any:
        ...
    


class CsArm64(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> tuple[Unknown, Unknown, Unknown, list[Any]]:
    ...

