"""
This type stub file was generated by pyright.
"""

import ctypes
from .evm_const import *

class CsEvm(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> tuple[Unknown, Unknown, Unknown]:
    ...

