"""
This type stub file was generated by pyright.
"""

import ctypes
from .m680x_const import *

class M680xOpIdx(ctypes.Structure):
    _fields_ = ...


class M680xOpRel(ctypes.Structure):
    _fields_ = ...


class M680xOpExt(ctypes.Structure):
    _fields_ = ...


class M680xOpValue(ctypes.Union):
    _fields_ = ...


class M680xOp(ctypes.Structure):
    _fields_ = ...
    @property
    def imm(self): # -> Any:
        ...
    
    @property
    def reg(self): # -> Any:
        ...
    
    @property
    def idx(self): # -> Any:
        ...
    
    @property
    def rel(self): # -> Any:
        ...
    
    @property
    def ext(self): # -> Any:
        ...
    
    @property
    def direct_addr(self): # -> Any:
        ...
    
    @property
    def const_val(self): # -> Any:
        ...
    


class CsM680x(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> tuple[Unknown, list[Any]]:
    ...

