"""
This type stub file was generated by pyright.
"""

import ctypes
from .mips_const import *

class MipsOpMem(ctypes.Structure):
    _fields_ = ...


class MipsOpValue(ctypes.Union):
    _fields_ = ...


class MipsOp(ctypes.Structure):
    _fields_ = ...
    @property
    def imm(self): # -> Any:
        ...
    
    @property
    def reg(self): # -> Any:
        ...
    
    @property
    def mem(self): # -> Any:
        ...
    


class CsMips(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> list[Any]:
    ...

