"""
This type stub file was generated by pyright.
"""

import ctypes
from .ppc_const import *

class PpcOpMem(ctypes.Structure):
    _fields_ = ...


class PpcOpCrx(ctypes.Structure):
    _fields_ = ...


class PpcOpValue(ctypes.Union):
    _fields_ = ...


class PpcOp(ctypes.Structure):
    _fields_ = ...
    @property
    def imm(self): # -> Any:
        ...
    
    @property
    def reg(self): # -> Any:
        ...
    
    @property
    def mem(self): # -> Any:
        ...
    
    @property
    def crx(self): # -> Any:
        ...
    


class CsPpc(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> tuple[Unknown, Unknown, Unknown, list[Any]]:
    ...

