"""
This type stub file was generated by pyright.
"""

import ctypes
from .sparc_const import *

class SparcOpMem(ctypes.Structure):
    _fields_ = ...


class SparcOpValue(ctypes.Union):
    _fields_ = ...


class SparcOp(ctypes.Structure):
    _fields_ = ...
    @property
    def imm(self): # -> Any:
        ...
    
    @property
    def reg(self): # -> Any:
        ...
    
    @property
    def mem(self): # -> Any:
        ...
    


class CsSparc(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> tuple[Unknown, Unknown, list[Any]]:
    ...

