"""
This type stub file was generated by pyright.
"""

import ctypes
from .sysz_const import *

class SyszOpMem(ctypes.Structure):
    _fields_ = ...


class SyszOpValue(ctypes.Union):
    _fields_ = ...


class SyszOp(ctypes.Structure):
    _fields_ = ...
    @property
    def imm(self): # -> Any:
        ...
    
    @property
    def reg(self): # -> Any:
        ...
    
    @property
    def mem(self): # -> Any:
        ...
    


class CsSysz(ctypes.Structure):
    _fields_ = ...


def get_arch_info(a): # -> tuple[Unknown, list[Any]]:
    ...

