name: "Build & Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: fzakaria
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop --command make lint
    - run: nix develop --command make test
    - run: nix build --print-build-logs
    - run: nix run . -- --help